ALTER TABLE MEASUREMENT
    MODIFY COLUMN measurement_id INT NOT NULL,
    MODIFY COLUMN person_id INT NOT NULL,
    MODIFY COLUMN measurement_concept_id INT NOT NULL,
    MODIFY COLUMN measurement_date DATE NOT NULL,
    MODIFY COLUMN measurement_datetime DATETIME NULL,
    MODIFY COLUMN measurement_time VARCHAR(10) NULL,
    MODIFY COLUMN measurement_type_concept_id INT NOT NULL,
    MODIFY COLUMN operator_concept_id INT NULL,
    MODIFY COLUMN value_as_number DECIMAL(18,5) NULL,
    MODIFY COLUMN value_as_concept_id INT NULL,
    MODIFY COLUMN unit_concept_id INT NULL,
    MODIFY COLUMN range_low DECIMAL(18,5) NULL,
    MODIFY COLUMN range_high DECIMAL(18,5) NULL,
    MODIFY COLUMN provider_id INT NULL,
    MODIFY COLUMN visit_occurrence_id INT NULL,
    MODIFY COLUMN visit_detail_id INT NULL,
    MODIFY COLUMN measurement_source_value VARCHAR(50) NULL,
    MODIFY COLUMN measurement_source_concept_id INT NULL,
    MODIFY COLUMN unit_source_value VARCHAR(50) NULL,
    MODIFY COLUMN unit_source_concept_id INT NULL,
    MODIFY COLUMN value_source_value VARCHAR(50) NULL,
    MODIFY COLUMN measurement_event_id BIGINT NULL,
    MODIFY COLUMN meas_event_field_concept_id INT NULL;

ALTER TABLE NOTE
    MODIFY COLUMN note_id INT NOT NULL,
    MODIFY COLUMN person_id INT NOT NULL,
    MODIFY COLUMN note_date DATE NOT NULL,
    MODIFY COLUMN note_datetime DATETIME NULL,
    MODIFY COLUMN note_type_concept_id INT NOT NULL,
    MODIFY COLUMN note_class_concept_id INT NOT NULL,
    MODIFY COLUMN note_title VARCHAR(250) NULL,
    MODIFY COLUMN note_text TEXT NOT NULL,
    MODIFY COLUMN encoding_concept_id INT NOT NULL,
    MODIFY COLUMN language_concept_id INT NOT NULL,
    MODIFY COLUMN provider_id INT NULL,
    MODIFY COLUMN visit_occurrence_id INT NULL,
    MODIFY COLUMN visit_detail_id INT NULL,
    MODIFY COLUMN note_source_value VARCHAR(50) NULL,
    MODIFY COLUMN note_event_id BIGINT NULL,
    MODIFY COLUMN note_event_field_concept_id INT NULL;

ALTER TABLE OBSERVATION
    MODIFY COLUMN value_as_concept_id INT NULL;
